language: node_js

cache: yarn

node_js:
  - "node"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set workspaces-experimental true

before_script:
  - yarn run gulp compile
